version: "3.9"
services:
  vertx-server-push:
    pull_policy: missing
    image: openjdk:17-slim
    container_name: vertx-server-push-build
    ports:
      - "13000:80"
    environment:
      - PUSH_PORT=80
      - JAVA_OPTS=
    labels:
      - "push-protocol=stomp"
      - 'framework=vertx'
    extra_hosts:
      - "googledns:8.8.8.8"
      - "dockerhub:52.1.157.61"
    expose:
      - 80
    restart: unless-stopped
    working_dir: /home
    volumes:
      - $PWD:/home/
      - $HOME/.m2:/root/.m2
      - $HOME/.gradle:/root/.gradle
    command: ./gradlew runShadow
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
