version: "3.9"
services:
  vertx-server-push:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: vertx-server-push
    ports:
      - "13000:80"
    environment:
      - PUSH_PORT=80
      - JAVA_OPTS=
    labels:
      - "push-protocol=stomp"
      - 'framework=vertx'
    extra_hosts:
      - "googledns:8.8.8.8"
      - "dockerhub:52.1.157.61"
    expose:
      - 80
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
